version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 100
    ignore:
      - dependency-name: "sphinx-jsonschema"  # Newer versions of sphinx-jsonschema have compatibility issues

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 100
