name: Documentation

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  Build:
    name: Build Documentation
    runs-on: ubuntu-latest
    
    steps:
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Checkout source
        uses: actions/checkout@master
        with:
          fetch-depth: 0 # Otherwise, you will fail to push refs to destination repo

      - name: Install dependencies
        run: pip install .[docs]

      - name: Build and commit
        uses: sphinx-notes/pages@master
        with:
          documentation_path: docs/source

      - name: Push changes
        if: github.event_name == 'push'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
