name: Documentation

on:
  pull_request:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v2

      - name: Build Docs
        working-directory: docs
        run: make html SPHINXOPTS="-W"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: docs/build/html

  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1