name: Packaging

on:
  pull_request:

jobs:
  packaging_tests:
    name: Run Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.7", "3.8", "3.9", "3.10" ] }

    steps:
      - name: Checkout source
        uses: actions/checkout@master

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install package dependencies
        run: |
          pip install pipx
          pipx install .

      - name: Confirm executable was installed
        run: notifier --version

  # Used for branch protections
  success:
    name: Tests were successful
    runs-on: ubuntu-latest
    needs: packaging_tests
    steps:
      - name: Mark tests successful
        run: echo "Tests were successful"