name: Tests

on:
  workflow_dispatch:
  workflow_call:
  push:

jobs:
  tests:
    name: Run Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.8", "3.9", "3.10", "3.11" ]

    steps:
      - name: Run Tests
        uses: ./.github/actions/tests
        with:
          python-version: ${{ matrix.python-version }}
          codacy-token: ${{ secrets.CODACY_PROJECT_TOKEN }}

  # Use this job for branch protection rules
  report-test-status:
    name: Report Test Status
    runs-on: ubuntu-latest
    needs: tests
    if: always()
    steps:
      - name: Check build status
        if: ${{ contains(needs.*.result, 'failure') }}
        run: exit 1

  # Tell codacy we are done reporting test coverage
  codacy-coverage-reporter:
    name: Report Code Coverage
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Finish reporting coverage
        run: bash <(curl -Ls https://coverage.codacy.com/get.sh) final
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
