name: Publish Package

on:
  release:
    types: [ released ]

jobs:
  test:
    name: Run Tests
    uses: ./.github/workflows/Unittests.yml
    secrets: inherit

  build:
    name: Build Source Distribution
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Poetry
        run: pip install poetry

      # Get the new package version from the release tag
      # Release tags are expected to start with a "v", so the first character is stripped
      - name: Set package version
        run: |
          tag=${{github.ref}}
          poetry version "${tag:1}"

      - name: Build package
        run: poetry build -v

      - name: Upload distribution to artifact storage
        uses: actions/upload-artifact@v3
        with:
          name: package-build
          path: dist
          retention-days: 7

  publish:
    name: Publish Distribution
    needs: build
    runs-on: ubuntu-latest
    environment: ${{ matrix.environment }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - host: https://py00.crc.pitt.edu
            environment: publish-h2p

    steps:
      - name: Download distribution from artifact storage
        uses: actions/download-artifact@v3
        with:
          name: package-build
          path: dist

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verbose: true
          repository_url: ${{ matrix.host }}
          user: ${{ secrets.REPO_USER }}
          password: ${{ secrets.REPO_PASSWORD }}
