name: Publish Package

on:
  release:
    types: [ released ]

jobs:
  test:
    name: Run Tests
    uses: ./.github/workflows/Unittests.yml
    secrets: inherit

  build:
    name: Build Source Distribution
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build package
        run: python -m build

      - name: Upload distribution to artifact storage
        uses: actions/upload-artifact@v3
        with:
          name: package-build
          path: dist
          retention-days: 7

  publish:
    name: Publish Distribution
    needs: build
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        environment: [ publish-h2p ]

    steps:
      - name: Download distribution from artifact storage
        uses: actions/download-artifact@v3
        with:
          name: package-build

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
        with:
          print_hash: true
          repository_url: ${{ secrets.REPO_URL }}
          user: ${{ secrets.REPO_USER }}
          password: ${{ secrets.REPO_PASSWORD }}
